{{- range $key, $value := .Values }}
{{- if and (eq $value.deployment "deployment") $value.autoscaling }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $key }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $key }}
  minReplicas: {{ $value.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ $value.autoscaling.maxReplicas | default 10 }}
  metrics:
  {{- with $value.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ . }}
  {{- end }}
  {{- with $value.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ . }}
  {{- end }}
{{- end }}
{{- end }}