{{- range $key, $value := .Values }}
{{- if $value.ingress }}
{{- with $value.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $key }}-ingress
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .ingressClassName }}
  ingressClassName: {{ .ingressClassName }}
  {{- end }}
  tls:
  - hosts:
    - {{ $value.host }}
    secretName: {{ $key }}-tls-secret
  rules:
  - host: {{ $value.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ $key }}-service
            port:
              number: {{ index $value.services 0 "port" }}
{{- end }}
{{- end }}
---
{{- end }}