paste:
  repository: ghcr.io/jonasbg/paste
  tag: "latest"
  deployment: deployment
  mounts:
  - name: uploads
    mountPath: /uploads
    readOnly: false
    storage: 10Gi
  host: chase.example.com
  env:
  - name: UPLOAD_DIR
    value: "/uploads"
  - name: FILES_RETENTION_DAYS
    value: "7"
  services:
  - name: http
    port: 8080
